### ISSUE TITLE
'charmap' codec can't decode byte 0x81 in position 1252

### ISSUE THREAD

**Issue by dominicdill** [vincentarelbundock/pycountrycode#12]
I've installed countrycode into an anaconda environment and used it successfully within a juyter notebook.

When I try to import countrycode via a .py file or from my terminal I am getting the following error

```
>>> import countrycode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\domin\anaconda3\envs\wsp\Lib\site-packages\countrycode\__init__.py", line 1, in <module>
    from .countrycode import codelist, countrycode
  File "C:\Users\domin\anaconda3\envs\wsp\Lib\site-packages\countrycode\countrycode.py", line 19, in <module>
    codelist = {col[0]: list(col[1:]) for col in zip(*rows)}
                                                 ^^^^^^^^^^
  File "C:\Users\domin\anaconda3\envs\wsp\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1252: character maps to <undefined>
```

**Comment by vincentarelbundock** [comment]
Thanks for the report. I have not tested this workflow and have designed the package to be installed via `pip` and friends.

If you have an easy solution to suggest, I can try to implement it, but otherwise this is unlikely to change.

**Comment by vincentarelbundock** [comment]
AFAICT, this is the only `open` call in the package, and it specifies `utf-8`

https://github.com/vincentarelbundock/pycountrycode/blob/ba675551fe85565975a79626f3640a4716896f19/countrycode/countrycode.py#L17

**Comment by raffaem** [comment]
I can confirm that the git version works. A new PyPi version should be issued
